project:
  type: website

website:
  site-url: https://iqb-vocabs.github.io/p60/
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-vocabs/p60/
  navbar:
    logo: IQB-klein.png
    search: true
    left:
        - href: index.qmd
          text: "BT-Frageb√∂gen"
    right:
        - icon: github
          href: https://github.com/iqb-vocabs/p60
          aria-label: Source Code

lang: de

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
